Name :- Anjali Srivastava

Registration Number :- 21BDS0069

Institution Name :- VIT Vellore

Slot :- 6:00pm - 8:00pm(Evening Slot)

# **Task - 1 Create a pandas dataframe (DataFrame name as 'df') (10 observation and 5 features)**

In [1]:
import pandas as pd
import numpy as np
d={'name':['A','B','C','D','E','F','G','H','I','J'],'Age':[19,20,21,18,22,26,14,28,17,16],'Gender':['M','F','F','M','M','M','F','M','F','F'],
   'Department':['Mechanical','Robotics','Zoology','Geography','Mathematics','Civil','Chemistry','Physics','Electronics','Telecommunication'],
   'Salary':[65000,90000,100000,85000,52000,63000,58000,98000,99000,75000]}
d

{'name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
 'Age': [19, 20, 21, 18, 22, 26, 14, 28, 17, 16],
 'Gender': ['M', 'F', 'F', 'M', 'M', 'M', 'F', 'M', 'F', 'F'],
 'Department': ['Mechanical',
  'Robotics',
  'Zoology',
  'Geography',
  'Mathematics',
  'Civil',
  'Chemistry',
  'Physics',
  'Electronics',
  'Telecommunication'],
 'Salary': [65000,
  90000,
  100000,
  85000,
  52000,
  63000,
  58000,
  98000,
  99000,
  75000]}

In [2]:
df=pd.DataFrame(d)
df

  name  Age Gender         Department  Salary
0    A   19      M         Mechanical   65000
1    B   20      F           Robotics   90000
2    C   21      F            Zoology  100000
3    D   18      M          Geography   85000
4    E   22      M        Mathematics   52000
5    F   26      M              Civil   63000
6    G   14      F          Chemistry   58000
7    H   28      M            Physics   98000
8    I   17      F        Electronics   99000
9    J   16      F  Telecommunication   75000

## **Task- 2 Check the info of 'df'**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   Age         10 non-null     int64
 2   Gender      10 non-null     object
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(2), object(3)
memory usage: 528.0+ bytes

# **Task 3- Check the descriptive statistics of 'df'**

In [5]:
df.describe()

             Age         Salary
count  10.000000      10.000000
mean   20.100000   78500.000000
std     4.357624   18240.674939
min    14.000000   52000.000000
25%    17.250000   63500.000000
50%    19.500000   80000.000000
75%    21.750000   96000.000000
max    28.000000  100000.000000

# **Task 4- check the 4th index observation with 'loc' slicing operator.**

In [6]:
df.loc[4]

name                    E
Age                    22
Gender                  M
Department    Mathematics
Salary              52000
Name: 4, dtype: object

# Task 5 - Check the null values in your 'df'

In [7]:
df.isnull().any()

name          False
Age           False
Gender        False
Department    False
Salary        False
dtype: bool